<?php

namespace App\Helpers\TransactionReport;

class JoReportHelper
{
    const REPORT_TABLE_HEADERS = [
        [
            'name' => 'S. No',
            'field' => 'DT_RowIndex',
            'header_class' => '',
            'column_class' => '',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Series',
            'field' => 'book_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Doc No',
            'field' => 'document_number',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Date',
            'field' => 'document_date',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Location',
            'field' => 'store_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Job Order Type',
            'field' => 'job_order_type',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Name',
            'field' => 'item_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Code',
            'field' => 'item_code',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Attributes',
            'field' => 'item_attributes',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'HSN',
            'field' => 'hsn_code',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'UOM',
            'field' => 'uom_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Order Qty',
            'field' => 'jo_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Short Closed Qty',
            'field' => 'short_close_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'GE Qty',
            'field' => 'ge_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'GRN Qty',
            'field' => 'grn_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Service Item',
            'field' => 'service_item',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Service Charge',
            'field' => 'service_charge',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Taxable Amt',
            'field' => 'taxable_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Tax',
            'field' => 'tax_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Total',
            'field' => 'total_item_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Status',
            'field' => 'status',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => 'text-align:center',
            'column_style' => '',
        ],
    ];

    const REPORT_FILTERS = [
        [
            'colSpan' => 'auto',
            'label' => 'Vendor',
            'id' => 'vendor_filter',
            'requestName' => 'vendor_id',
            'term' => 'vendor_list',
            'value_key' => 'id',
            'label_key' => 'company_name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Series',
            'id' => 'book_filter',
            'requestName' => 'book_id',
            'term' => 'report_jo_book',
            'value_key' => 'id',
            'label_key' => 'book_code',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Doc No',
            'id' => 'doc_number_filter',
            'requestName' => 'document_number',
            'term' => 'report_jo_documents',
            'value_key' => 'id',
            'label_key' => 'document_number',
            'type' => 'input_text'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Item Category',
            'id' => 'item_cat_filter',
            'requestName' => 'item_category_id',
            'term' => 'category',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['item_sub_cat_filter', 'item_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Item Sub Category',
            'id' => 'item_sub_cat_filter',
            'requestName' => 'item_sub_category_id',
            'term' => 'subcategory',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['item_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Items',
            'id' => 'item_filter',
            'requestName' => 'item_id',
            'term' => 'report_items',
            'value_key' => 'id',
            'label_key' => 'item_name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Status',
            'id' => 'doc_status_filter',
            'requestName' => 'doc_status',
            'term' => 'document_statuses',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Company',
            'id' => 'company_filter',
            'requestName' => 'company_id',
            'term' => 'companies',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['organization_filter']

        ],
        [
            'colSpan' => 'auto',
            'label' => 'Organization',
            'id' => 'organization_filter',
            'requestName' => 'organization_id',
            'term' => 'organizations',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['location_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Location',
            'id' => 'location_filter',
            'requestName' => 'location_id',
            'term' => 'location',
            'value_key' => 'id',
            'label_key' => 'store_name',
            'type' => 'auto_complete'
        ],
    ];
}
