<?php

namespace App\Helpers\TransactionReport;
use App\Models\Legal;

class rcReportHelper
{
    const RC_TABLE_HEADERS = [
        [
            'name' => 'S. No',
            'field' => 'DT_RowIndex',
            'header_class' => '',
            'column_class' => '',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Series',
            'field' => 'book_code',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Document No',
            'field' => 'document_number',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Date',
            'field' => 'document_date',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'party_type',
            'field' => 'party_type',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Party Name',
            'field' => 'party_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Category',
            'field' => 'category_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item type',
            'field' => 'item_type',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item',
            'field' => 'item_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Code',
            'field' => 'item_code',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Attributes',
            'field' => 'item_attributes',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'UOM',
            'field' => 'uom',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'MOQ',
            'field' => 'moq',
            'header_class' => 'numeric-alignment',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'From Qty',
            'field' => 'from_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'To Qty',
            'field' => 'to_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Rate',
            'field' => 'rate',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Lead Time',
            'field' => 'lead_time',
            'header_class' => 'numeric-alignment',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Effective From',
            'field' => 'effective_from',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Effective To',
            'field' => 'effective_to',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Applicable Orgs',
            'field' => 'applicable_orgs',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Status',
            'field' => 'status',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => 'text-align:center',
            'column_style' => '',
        ],
    ];
    const RC_FILTERS = [
        [
            'colSpan' => 'auto',
            'label' => 'Contract No',
            'id' => 'contract_filter',
            'requestName' => 'contract_no',
            'term' => 'rc_document_qt',
            'value_key' => 'id',
            'label_key' => 'document_number',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Item',
            'id' => 'item_filter',
            'requestName' => 'item_id',
            'term' => 'report_items',
            'value_key' => 'id',
            'label_key' => 'item_name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Party Type',
            'id' => 'party_type',
            'requestName' => 'party_type',
            'term' => 'party_type_filter',
            'value_key' => 'id',
            'label_key' => 'company_name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Party',
            'id' => 'party',
            'requestName' => 'party',
            'term' => 'party_filter',
            'value_key' => 'id',
            'label_key' => 'company_name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Effective Date ',
            'id' => 'effective_date',
            'requestName' => 'effective_date',
            'term' => '',
            'value_key' => '',
            'label_key' => '',
            'type' => 'date_range'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Item Category',
            'id' => 'm_category_id',
            'requestName' => 'm_category_id',
            'term' => 'category',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['m_subcategory_id', 'item_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Status',
            'id' => 'status',
            'requestName' => 'status',
            'term' => 'document_statuses',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Item Sub Category',
            'id' => 'm_subcategory_id',
            'requestName' => 'm_subcategory_id',
            'term' => 'subcategory',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['item_filter']
        ],
    ];
}