<?php

namespace App\Helpers\TransactionReport;
use App\Models\Legal;

class rfqReportHelper
{
    const RFQ_TABLE_HEADERS = [
        [
            'name' => 'S. No',
            'field' => 'DT_RowIndex',
            'header_class' => '',
            'column_class' => '',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Series',
            'field' => 'book_code',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Purchase Return No',
            'field' => 'document_number',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Purchase Return Date',
            'field' => 'document_date',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'MRN NO',
            'field' => 'mrn_no',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'SO No',
            'field' => 'so_no',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Vendor',
            'field' => 'vendor_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Vendor Rating',
            'field' => 'vendor_rating',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Category',
            'field' => 'category_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Sub Category',
            'field' => 'sub_category_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item type',
            'field' => 'item_type',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Sub type',
            'field' => 'sub_type',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item',
            'field' => 'item_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Code',
            'field' => 'item_code',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Type',
            'field' => 'qty_return_type',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Order Qty',
            'field' => 'accepted_qty',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Rate',
            'field' => 'rate',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Basic Value',
            'field' => 'basic_value',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Discount',
            'field' => 'item_discount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Header Discount',
            'field' => 'header_discount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Amount',
            'field' => 'item_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Status',
            'field' => 'status',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => 'text-align:center',
            'column_style' => '',
        ],
    ];
    const RFQ_FILTERS = [
        [
            'colSpan' => 'auto',
            'label' => 'MRN No',
            'id' => 'mrn_no',
            'requestName' => 'mrn_no',
            'term' => 'mrn_document_qt',
            'value_key' => 'id',
            'label_key' => 'document_number',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'SO No',
            'id' => 'so_no',
            'requestName' => 'so_no',
            'term' => 'report_so_documents',
            'value_key' => 'id',
            'label_key' => 'document_number',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Item',
            'id' => 'item_filter',
            'requestName' => 'item_id',
            'term' => 'report_items',
            'value_key' => 'id',
            'label_key' => 'item_name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Status',
            'id' => 'status',
            'requestName' => 'status',
            'term' => 'document_statuses',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Vendor',
            'id' => 'vendor',
            'requestName' => 'vendor',
            'term' => 'vendor_mi',
            'value_key' => 'id',
            'label_key' => 'company_name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Item Category',
            'id' => 'm_category_id',
            'requestName' => 'm_category_id',
            'term' => 'category',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['m_subcategory_id', 'item_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Item Sub Category',
            'id' => 'm_subcategory_id',
            'requestName' => 'm_subcategory_id',
            'term' => 'subcategory',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['item_filter']
        ],
    ];
}
