<?php

namespace App\Helpers;

use App\Helpers\TransactionReport\expenseReportHelper;
use App\Helpers\TransactionReport\geReportHelper;
use App\Helpers\TransactionReport\mrnReportHelper;
use App\Helpers\TransactionReport\pbReportHelper;
use App\Helpers\TransactionReport\pqReportHelper;
use App\Helpers\TransactionReport\prReportHelper;
use App\Helpers\TransactionReport\plReportHelper;
use App\Helpers\TransactionReport\bomReportHelper;
use App\Helpers\TransactionReport\moReportHelper;
use App\Helpers\TransactionReport\rfqReportHelper;

class TransactionReportHelper
{
    //Report filter routes mapping
    public static array $TABLE_HEADERS = [];

    const FILTER_ROUTES = [
        ConstantHelper::SO_SERVICE_ALIAS => 'sale.order.report',
        ConstantHelper::SO_SERVICE_ALIAS . 'attributeGrouped' => 'sale.order.report.attribute.grouped',
        ConstantHelper::SI_SERVICE_ALIAS => 'sale.invoice.report',
        ConstantHelper::SR_SERVICE_ALIAS => 'sale.return.report',
        ConstantHelper::MATERIAL_RETURN_SERVICE_ALIAS_NAME => 'material.return.report',
        ConstantHelper::MATERIAL_ISSUE_SERVICE_ALIAS_NAME => 'mi.report',
        ConstantHelper::MRN_SERVICE_ALIAS => 'material-receipt.order.report',
        ConstantHelper::GATE_ENTRY_SERVICE_ALIAS => 'gate-entry.order.report',
        ConstantHelper::EXPENSE_ADVISE_SERVICE_ALIAS => 'expense-adv.order.report',
        ConstantHelper::PB_SERVICE_ALIAS => 'purchase-bill.order.report',
        ConstantHelper::PURCHASE_RETURN_SERVICE_ALIAS => 'purchase-return.order.report',
        ConstantHelper::PSV_SERVICE_ALIAS => 'psv.report',
        ConstantHelper::PO_SERVICE_ALIAS => 'po.report,{"type":"purchase-order"}',
        ConstantHelper::PI_SERVICE_ALIAS => 'pi.report',
        ConstantHelper::PL_SERVICE_ALIAS => 'PL.report',
        ConstantHelper::MO_SERVICE_ALIAS => 'mo.report',
        ConstantHelper::BOM_SERVICE_ALIAS => 'bill.of.material.report',
        ConstantHelper::RFQ_SERVICE_ALIAS => 'rfq.report',
        ConstantHelper::PQ_SERVICE_ALIAS => 'pq.report',
    ];
    const INDEX_ROUTES = [
        ConstantHelper::SO_SERVICE_ALIAS => 'sale.order.index',
        ConstantHelper::SI_SERVICE_ALIAS => 'sale.invoice.index',
        ConstantHelper::SR_SERVICE_ALIAS => 'sale.return.index',
        ConstantHelper::MATERIAL_RETURN_SERVICE_ALIAS_NAME => 'material.return.index',
        ConstantHelper::MATERIAL_ISSUE_SERVICE_ALIAS_NAME => 'material.issue.index',
        ConstantHelper::PSV_SERVICE_ALIAS => 'psv.index',
        ConstantHelper::PO_SERVICE_ALIAS => 'po.index',
        ConstantHelper::PI_SERVICE_ALIAS => 'pi.index',
        ConstantHelper::PL_SERVICE_ALIAS => 'PL.index',
        ConstantHelper::MO_SERVICE_ALIAS => 'mo.index',
        ConstantHelper::BOM_SERVICE_ALIAS => 'bom.index',
        ConstantHelper::RFQ_SERVICE_ALIAS => 'rfq.index',
        ConstantHelper::PQ_SERVICE_ALIAS => 'pq.index',
    ];
    const SO_TABLE_HEADERS = [
        [
            'name' => 'S. No',
            'field' => 'DT_RowIndex',
            'header_class' => '',
            'column_class' => '',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Series',
            'field' => 'book_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Doc No',
            'field' => 'document_number',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Date',
            'field' => 'document_date',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Location',
            'field' => 'store_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Customer',
            'field' => 'customer_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Currency',
            'field' => 'customer_currency',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Name',
            'field' => 'item_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Code',
            'field' => 'item_code',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Attributes',
            'field' => 'item_attributes',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'HSN',
            'field' => 'hsn_code',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'UOM',
            'field' => 'uom_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Order Qty',
            'field' => 'so_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Rate',
            'field' => 'rate',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Discount',
            'field' => 'total_discount_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Taxable Amt',
            'field' => 'taxable_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Tax',
            'field' => 'tax_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Total',
            'field' => 'total_item_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Delivery Date',
            'field' => 'delivery_schedule',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'PWO Qty',
            'field' => 'pwo_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Produced Qty',
            'field' => 'pslip_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Invoiced Qty',
            'field' => 'invoice_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Returned Qty',
            'field' => 'srn_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Short Closed Qty',
            'field' => 'srn_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Pending Qty',
            'field' => 'pending_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Status',
            'field' => 'status',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => 'text-align:center',
            'column_style' => '',
        ],
    ];

    const SO_ATTRIBUTE_GROUPED_TABLE_HEADERS = [
        [
            'name' => 'S. No',
            'field' => 'DT_RowIndex',
            'header_class' => '',
            'column_class' => '',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Series',
            'field' => 'book_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Doc No',
            'field' => 'document_number',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Date',
            'field' => 'document_date',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Location',
            'field' => 'store_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Customer',
            'field' => 'customer_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Currency',
            'field' => 'customer_currency',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Name',
            'field' => 'item_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Code',
            'field' => 'item_code',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Category',
            'field' => 'item_category',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        //Specs
        [
            'name' => 'Brand',
            'field' => 'brand_CUSTOMSPECCODE',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Model',
            'field' => 'model_CUSTOMSPECCODE',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'India PGSC',
            'field' => 'pgsc_CUSTOMSPECCODE',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Colorway',
            'field' => 'colourway_CUSTOMSPECCODE',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Gender',
            'field' => 'gender_CUSTOMSPECCODE',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Last No.',
            'field' => 'last_CUSTOMSPECCODE',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Season',
            'field' => 'season_CUSTOMSPECCODE',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Tooling Name',
            'field' => 'tooling_CUSTOMSPECCODE',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Construction',
            'field' => 'construction_CUSTOMSPECCODE',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Mean Size',
            'field' => 'mean_size',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Batch No.',
            'field' => 'batch_no',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'HSN',
            'field' => 'hsn_code',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'UOM',
            'field' => 'uom_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Total Order Qty',
            'field' => 'so_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Final CRD',
            'field' => 'finalcrd_CUSTOMONLY',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Rate',
            'field' => 'rate',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Discount',
            'field' => 'total_discount_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Taxable Amt',
            'field' => 'taxable_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Tax',
            'field' => 'tax_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Total',
            'field' => 'total_item_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'PO Expiry',
            'field' => 'delivery_schedule',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'PWO Qty',
            'field' => 'pwo_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Produced Qty',
            'field' => 'pslip_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Invoiced Qty',
            'field' => 'invoice_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Returned Qty',
            'field' => 'srn_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Short Closed Qty',
            'field' => 'srn_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Pending Qty',
            'field' => 'pending_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Remark',
            'field' => 'doc_remarks',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Status',
            'field' => 'status',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => 'text-align:center',
            'column_style' => '',
        ],
    ];
    const SO_FILTERS = [
        [
            'colSpan' => 'auto',
            'label' => 'Customer',
            'id' => 'customer_filter',
            'requestName' => 'customer_id',
            'term' => 'customer',
            'value_key' => 'id',
            'label_key' => 'company_name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Series',
            'id' => 'book_filter',
            'requestName' => 'book_id',
            'term' => 'report_so_book',
            'value_key' => 'id',
            'label_key' => 'book_code',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Doc No',
            'id' => 'doc_number_filter',
            'requestName' => 'document_number',
            'term' => 'report_so_documents',
            'value_key' => 'id',
            'label_key' => 'document_number',
            'type' => 'input_text'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Delivery Date',
            'id' => 'delivery_date_filter',
            'requestName' => 'delivery_date_range',
            'term' => '',
            'value_key' => '',
            'label_key' => '',
            'type' => 'date_range'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Item Category',
            'id' => 'item_cat_filter',
            'requestName' => 'item_category_id',
            'term' => 'category',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['item_sub_cat_filter', 'item_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Item Sub Category',
            'id' => 'item_sub_cat_filter',
            'requestName' => 'item_sub_category_id',
            'term' => 'subcategory',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['item_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Items',
            'id' => 'item_filter',
            'requestName' => 'item_id',
            'term' => 'report_items',
            'value_key' => 'id',
            'label_key' => 'item_name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Status',
            'id' => 'doc_status_filter',
            'requestName' => 'doc_status',
            'term' => 'document_statuses',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Company',
            'id' => 'company_filter',
            'requestName' => 'company_id',
            'term' => 'companies',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['organization_filter']

        ],
        [
            'colSpan' => 'auto',
            'label' => 'Organization',
            'id' => 'organization_filter',
            'requestName' => 'organization_id',
            'term' => 'organizations',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['location_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Location',
            'id' => 'location_filter',
            'requestName' => 'location_id',
            'term' => 'location',
            'value_key' => 'id',
            'label_key' => 'store_name',
            'type' => 'auto_complete'
        ],
    ];
    const SI_TABLE_HEADERS = [
        [
            'name' => 'S. No',
            'field' => 'DT_RowIndex',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Series',
            'field' => 'book_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Doc No',
            'field' => 'document_number',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Date',
            'field' => 'document_date',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Location',
            'field' => 'store_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Customer',
            'field' => 'customer_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Currency',
            'field' => 'customer_currency',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Name',
            'field' => 'item_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Code',
            'field' => 'item_code',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Attributes',
            'field' => 'item_attributes',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'HSN',
            'field' => 'hsn_code',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'UOM',
            'field' => 'uom_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Invoice Qty',
            'field' => 'si_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Rate',
            'field' => 'rate',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Discount',
            'field' => 'total_discount_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Taxable Amt',
            'field' => 'taxable_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Tax',
            'field' => 'tax_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Total',
            'field' => 'total_item_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],

        [
            'name' => 'Order No',
            'field' => 'so_no',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => 'text-align:center',
            'column_style' => '',
        ],
        [
            'name' => 'Order Dt',
            'field' => 'so_date',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => 'text-align:center',
            'column_style' => '',
        ],

        [
            'name' => 'Order Qty',
            'field' => 'so_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Returned Qty',
            'field' => 'srn_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Status',
            'field' => 'status',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => 'text-align:center',
            'column_style' => '',
        ],
    ];
    const SI_FILTERS = [
        [
            'colSpan' => 'auto',
            'label' => 'Customer',
            'id' => 'customer_filter',
            'requestName' => 'customer_id',
            'term' => 'customer',
            'value_key' => 'id',
            'label_key' => 'company_name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Series',
            'id' => 'book_filter',
            'requestName' => 'book_id',
            'term' => 'report_si_book',
            'value_key' => 'id',
            'label_key' => 'book_code',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Doc No',
            'id' => 'doc_number_filter',
            'requestName' => 'document_number',
            'term' => 'report_si_documents',
            'value_key' => 'id',
            'label_key' => 'document_number',
            'type' => 'input_text'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Order No',
            'id' => 'order_no_filter',
            'requestName' => 'so_no',
            'term' => '',
            'value_key' => '',
            'label_key' => '',
            'type' => 'input_text',
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Order Dt',
            'id' => 'order_dt_filter',
            'requestName' => 'so_dt',
            'term' => '',
            'value_key' => '',
            'label_key' => '',
            'type' => 'date_range',
        ],

        [
            'colSpan' => 'auto',
            'label' => 'Item Category',
            'id' => 'item_cat_filter',
            'requestName' => 'item_category_id',
            'term' => 'category',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['item_sub_cat_filter', 'item_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Item Sub Category',
            'id' => 'item_sub_cat_filter',
            'requestName' => 'item_sub_category_id',
            'term' => 'subcategory',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['item_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Items',
            'id' => 'item_filter',
            'requestName' => 'item_id',
            'term' => 'report_items',
            'value_key' => 'id',
            'label_key' => 'item_name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Status',
            'id' => 'doc_status_filter',
            'requestName' => 'doc_status',
            'term' => 'document_statuses',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Company',
            'id' => 'company_filter',
            'requestName' => 'company_id',
            'term' => 'companies',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['organization_filter']

        ],
        [
            'colSpan' => 'auto',
            'label' => 'Organization',
            'id' => 'organization_filter',
            'requestName' => 'organization_id',
            'term' => 'organizations',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['location_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Location',
            'id' => 'location_filter',
            'requestName' => 'location_id',
            'term' => 'location',
            'value_key' => 'id',
            'label_key' => 'store_name',
            'type' => 'auto_complete'
        ],
    ];

    const SR_TABLE_HEADERS = [
        [
            'name' => 'S. No',
            'field' => 'DT_RowIndex',
            'header_class' => '',
            'column_class' => '',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Series',
            'field' => 'book_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Doc No',
            'field' => 'document_number',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Date',
            'field' => 'document_date',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Location',
            'field' => 'store_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Customer',
            'field' => 'customer_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Currency',
            'field' => 'customer_currency',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Name',
            'field' => 'item_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Code',
            'field' => 'item_code',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Attributes',
            'field' => 'item_attributes',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'HSN',
            'field' => 'hsn_code',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'UOM',
            'field' => 'uom_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Returned Qty',
            'field' => 'sr_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Rate',
            'field' => 'rate',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Discount',
            'field' => 'total_discount_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Taxable Amt',
            'field' => 'taxable_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Tax',
            'field' => 'tax_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Total',
            'field' => 'total_item_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Invoice No',
            'field' => 'si_no',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => 'text-align:center',
            'column_style' => '',
        ],
        [
            'name' => 'Invoice Dt',
            'field' => 'si_date',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => 'text-align:center',
            'column_style' => '',
        ],

        [
            'name' => 'Invoice Qty',
            'field' => 'si_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Order No',
            'field' => 'so_no',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => 'text-align:center',
            'column_style' => '',
        ],
        [
            'name' => 'Order Dt',
            'field' => 'so_date',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => 'text-align:center',
            'column_style' => '',
        ],

        [
            'name' => 'Order Qty',
            'field' => 'so_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Status',
            'field' => 'status',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => 'text-align:center',
            'column_style' => '',
        ],
    ];
    const SR_FILTERS = [
        [
            'colSpan' => 'auto',
            'label' => 'Customer',
            'id' => 'customer_filter',
            'requestName' => 'customer_id',
            'term' => 'customer',
            'value_key' => 'id',
            'label_key' => 'company_name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Series',
            'id' => 'book_filter',
            'requestName' => 'book_id',
            'term' => 'report_so_book',
            'value_key' => 'id',
            'label_key' => 'book_code',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Doc No',
            'id' => 'doc_number_filter',
            'requestName' => 'document_number',
            'term' => 'report_so_documents',
            'value_key' => 'id',
            'label_key' => 'document_number',
            'type' => 'input_text'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Order No',
            'id' => 'order_no_filter',
            'requestName' => 'so_no',
            'term' => '',
            'value_key' => '',
            'label_key' => '',
            'type' => 'input_text',
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Order Dt',
            'id' => 'order_dt_filter',
            'requestName' => 'so_dt',
            'term' => '',
            'value_key' => '',
            'label_key' => '',
            'type' => 'date_range',
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Invoice No',
            'id' => 'invoice_no_filter',
            'requestName' => 'si_no',
            'term' => '',
            'value_key' => '',
            'label_key' => '',
            'type' => 'input_text',
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Invoice Dt',
            'id' => 'invoice_dt_filter',
            'requestName' => 'si_dt',
            'term' => '',
            'value_key' => '',
            'label_key' => '',
            'type' => 'date_range',
        ],

        [
            'colSpan' => 'auto',
            'label' => 'Item Category',
            'id' => 'item_cat_filter',
            'requestName' => 'item_category_id',
            'term' => 'category',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['item_sub_cat_filter', 'item_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Item Sub Category',
            'id' => 'item_sub_cat_filter',
            'requestName' => 'item_sub_category_id',
            'term' => 'subcategory',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['item_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Items',
            'id' => 'item_filter',
            'requestName' => 'item_id',
            'term' => 'report_items',
            'value_key' => 'id',
            'label_key' => 'item_name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Status',
            'id' => 'doc_status_filter',
            'requestName' => 'doc_status',
            'term' => 'document_statuses',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Company',
            'id' => 'company_filter',
            'requestName' => 'company_id',
            'term' => 'companies',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['organization_filter']

        ],
        [
            'colSpan' => 'auto',
            'label' => 'Organization',
            'id' => 'organization_filter',
            'requestName' => 'organization_id',
            'term' => 'organizations',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['location_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Location',
            'id' => 'location_filter',
            'requestName' => 'location_id',
            'term' => 'location',
            'value_key' => 'id',
            'label_key' => 'store_name',
            'type' => 'auto_complete'
        ],
    ];
    const MATERIAL_RETURN_SERVICE_ALIAS_NAME_TABLE_HEADERS = [
        [
            'name' => 'S. No',
            'field' => 'DT_RowIndex',
            'header_class' => '',
            'column_class' => '',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Series',
            'field' => 'book_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Doc No',
            'field' => 'document_number',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Doc Type',
            'field' => 'return_type',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Date',
            'field' => 'document_date',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'From Location',
            'field' => 'from_store_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'To Location',
            'field' => 'to_store_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'From Sub Location',
            'field' => 'from_sub_store_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'To Sub Location',
            'field' => 'to_sub_store_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Vendor',
            'field' => 'vendor_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Requester',
            'field' => 'requester',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Currency',
            'field' => 'customer_currency',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Name',
            'field' => 'item_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Code',
            'field' => 'item_code',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Attributes',
            'field' => 'item_attributes',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'HSN',
            'field' => 'hsn_code',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'UOM',
            'field' => 'uom_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Returned Qty',
            'field' => 'qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Rate',
            'field' => 'rate',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        // [
        //     'name' => 'Discount',
        //     'field' => 'total_discount_amount',
        //     'header_class' => 'numeric-alignment',
        //     'column_class' => 'text-end',
        //     'header_style' => '',
        //     'column_style' => '',
        // ],
        // [
        //     'name' => 'Taxable Amt',
        //     'field' => 'taxable_amount',
        //     'header_class' => 'numeric-alignment',
        //     'column_class' => 'text-end',
        //     'header_style' => '',
        //     'column_style' => '',
        // ],
        // [
        //     'name' => 'Tax',
        //     'field' => 'tax_amount',
        //     'header_class' => 'numeric-alignment',
        //     'column_class' => 'text-end',
        //     'header_style' => '',
        //     'column_style' => '',
        // ],
        [
            'name' => 'Total',
            'field' => 'total_item_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Issue No',
            'field' => 'mi_no',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => 'text-align:center',
            'column_style' => '',
        ],
        [
            'name' => 'Issue Dt',
            'field' => 'mi_date',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => 'text-align:center',
            'column_style' => '',
        ],

        [
            'name' => 'Issue Qty',
            'field' => 'mi_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Status',
            'field' => 'status',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => 'text-align:center',
            'column_style' => '',
        ],
    ];
    const MATERIAL_RETURN_SERVICE_ALIAS_NAME_FILTERS = [
        [
            'colSpan' => 'auto',
            'label' => 'Vendor',
            'id' => 'vendor_filter',
            'requestName' => 'vendor_id',
            'term' => 'vendor_list',
            'value_key' => 'id',
            'label_key' => 'company_name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Series',
            'id' => 'book_filter',
            'requestName' => 'book_id',
            'term' => 'report_mr_book',
            'value_key' => 'id',
            'label_key' => 'book_code',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Doc No',
            'id' => 'doc_number_filter',
            'requestName' => 'document_number',
            'term' => 'report_mr_documents',
            'value_key' => 'id',
            'label_key' => 'document_number',
            'type' => 'input_text'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'issue No',
            'id' => 'issue_no_filter',
            'requestName' => 'mi_no',
            'term' => '',
            'value_key' => '',
            'label_key' => '',
            'type' => 'input_text',
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Return Dt',
            'id' => 'return_dt_filter',
            'requestName' => 'mi_dt',
            'term' => '',
            'value_key' => '',
            'label_key' => '',
            'type' => 'date_range',
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Item Category',
            'id' => 'item_cat_filter',
            'requestName' => 'item_category_id',
            'term' => 'category',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['item_sub_cat_filter', 'item_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Item Sub Category',
            'id' => 'item_sub_cat_filter',
            'requestName' => 'item_sub_category_id',
            'term' => 'subcategory',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['item_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Items',
            'id' => 'item_filter',
            'requestName' => 'item_id',
            'term' => 'report_items',
            'value_key' => 'id',
            'label_key' => 'item_name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Status',
            'id' => 'doc_status_filter',
            'requestName' => 'doc_status',
            'term' => 'document_statuses',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Company',
            'id' => 'company_filter',
            'requestName' => 'company_id',
            'term' => 'companies',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['organization_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Organization',
            'id' => 'organization_filter',
            'requestName' => 'organization_id',
            'term' => 'organizations',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['location_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'From Location',
            'id' => 'from_location_filter',
            'requestName' => 'from_location_id',
            'term' => 'location',
            'value_key' => 'id',
            'label_key' => 'store_name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'To Location',
            'id' => 'to_location_filter',
            'requestName' => 'to_location_id',
            'term' => 'location',
            'value_key' => 'id',
            'label_key' => 'store_name',
            'type' => 'auto_complete'
        ],
    ];
    const MATERIAL_ISSUE_SERVICE_ALIAS_NAME_TABLE_HEADERS = [
        [
            'name' => 'S. No',
            'field' => 'DT_RowIndex',
            'header_class' => '',
            'column_class' => '',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Series',
            'field' => 'book_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Doc No',
            'field' => 'document_number',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Doc Type',
            'field' => 'issue_type',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Date',
            'field' => 'document_date',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'From Location',
            'field' => 'from_store_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'To Location',
            'field' => 'to_store_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'From Sub Location',
            'field' => 'from_sub_store_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'To Sub Location',
            'field' => 'to_sub_store_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Vendor',
            'field' => 'vendor_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Requester',
            'field' => 'requester',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Currency',
            'field' => 'customer_currency',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Name',
            'field' => 'item_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Code',
            'field' => 'item_code',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Attributes',
            'field' => 'item_attributes',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'HSN',
            'field' => 'hsn_code',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'UOM',
            'field' => 'uom_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Qty',
            'field' => 'qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Rate',
            'field' => 'rate',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        // [
        //     'name' => 'Discount',
        //     'field' => 'total_discount_amount',
        //     'header_class' => 'numeric-alignment',
        //     'column_class' => 'text-end',
        //     'header_style' => '',
        //     'column_style' => '',
        // ],
        // [
        //     'name' => 'Taxable Amt',
        //     'field' => 'taxable_amount',
        //     'header_class' => 'numeric-alignment',
        //     'column_class' => 'text-end',
        //     'header_style' => '',
        //     'column_style' => '',
        // ],
        // [
        //     'name' => 'Tax',
        //     'field' => 'tax_amount',
        //     'header_class' => 'numeric-alignment',
        //     'column_class' => 'text-end',
        //     'header_style' => '',
        //     'column_style' => '',
        // ],
        [
            'name' => 'Total',
            'field' => 'total_item_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Returned Qty',
            'field' => 'mr_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Status',
            'field' => 'status',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => 'text-align:center',
            'column_style' => '',
        ],
    ];
    const MATERIAL_ISSUE_SERVICE_ALIAS_NAME_FILTERS = [
        [
            'colSpan' => 'auto',
            'label' => 'Vendor',
            'id' => 'vendor_filter',
            'requestName' => 'vendor_id',
            'term' => 'vendor_list',
            'value_key' => 'id',
            'label_key' => 'company_name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Series',
            'id' => 'book_filter',
            'requestName' => 'book_id',
            'term' => 'report_so_book',
            'value_key' => 'id',
            'label_key' => 'book_code',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Doc No',
            'id' => 'doc_number_filter',
            'requestName' => 'document_number',
            'term' => 'report_so_documents',
            'value_key' => 'id',
            'label_key' => 'document_number',
            'type' => 'input_text'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Item Category',
            'id' => 'item_cat_filter',
            'requestName' => 'item_category_id',
            'term' => 'category',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['item_sub_cat_filter', 'item_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Item Sub Category',
            'id' => 'item_sub_cat_filter',
            'requestName' => 'item_sub_category_id',
            'term' => 'subcategory',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['item_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Items',
            'id' => 'item_filter',
            'requestName' => 'item_id',
            'term' => 'report_items',
            'value_key' => 'id',
            'label_key' => 'item_name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Status',
            'id' => 'doc_status_filter',
            'requestName' => 'doc_status',
            'term' => 'document_statuses',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Company',
            'id' => 'company_filter',
            'requestName' => 'company_id',
            'term' => 'companies',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['organization_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Organization',
            'id' => 'organization_filter',
            'requestName' => 'organization_id',
            'term' => 'organizations',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['location_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'From Location',
            'id' => 'from_location_filter',
            'requestName' => 'from_location_id',
            'term' => 'location',
            'value_key' => 'id',
            'label_key' => 'store_name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'To Location',
            'id' => 'to_location_filter',
            'requestName' => 'to_location_id',
            'term' => 'location',
            'value_key' => 'id',
            'label_key' => 'store_name',
            'type' => 'auto_complete'
        ],
    ];

    const PSV_TABLE_HEADERS = [
        [
            'name' => 'S. No',
            'field' => 'DT_RowIndex',
            'header_class' => '',
            'column_class' => '',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Series',
            'field' => 'book_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Doc No',
            'field' => 'document_number',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Date',
            'field' => 'document_date',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Location',
            'field' => 'store_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Store',
            'field' => 'sub_store_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Currency',
            'field' => 'customer_currency',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Name',
            'field' => 'item_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Code',
            'field' => 'item_code',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Attributes',
            'field' => 'item_attributes',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'HSN',
            'field' => 'hsn_code',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'UOM',
            'field' => 'uom_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Physical Qty',
            'field' => 'physical_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Confirmed Stock',
            'field' => 'confirmed_stock',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Unconfirmed Stock',
            'field' => 'unconfirmed_stock',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Adjusted Qty',
            'field' => 'adjusted_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Rate',
            'field' => 'rate',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Total',
            'field' => 'total_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
    ];
    const PSV_FILTERS = [
        [
            'colSpan' => 'auto',
            'label' => 'Series',
            'id' => 'book_filter',
            'requestName' => 'book_id',
            'term' => 'report_psv_book',
            'value_key' => 'id',
            'label_key' => 'book_code',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Doc No',
            'id' => 'doc_number_filter',
            'requestName' => 'document_number',
            'term' => 'report_psv_documents',
            'value_key' => 'id',
            'label_key' => 'document_number',
            'type' => 'input_text'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Item Category',
            'id' => 'item_cat_filter',
            'requestName' => 'item_category_id',
            'term' => 'category',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['item_sub_cat_filter', 'item_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Item Sub Category',
            'id' => 'item_sub_cat_filter',
            'requestName' => 'item_sub_category_id',
            'term' => 'subcategory',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['item_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Items',
            'id' => 'item_filter',
            'requestName' => 'item_id',
            'term' => 'report_items',
            'value_key' => 'id',
            'label_key' => 'item_name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Status',
            'id' => 'doc_status_filter',
            'requestName' => 'doc_status',
            'term' => 'document_statuses',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Company',
            'id' => 'company_filter',
            'requestName' => 'company_id',
            'term' => 'companies',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['organization_filter']

        ],
        [
            'colSpan' => 'auto',
            'label' => 'Organization',
            'id' => 'organization_filter',
            'requestName' => 'organization_id',
            'term' => 'organizations',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['location_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Location',
            'id' => 'location_filter',
            'requestName' => 'location_id',
            'term' => 'location',
            'value_key' => 'id',
            'label_key' => 'store_name',
            'type' => 'auto_complete'
        ],
    ];
    const PO_TABLE_HEADERS = [
        [
            'name' => 'S. No',
            'field' => 'DT_RowIndex',
            'header_class' => '',
            'column_class' => '',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Series',
            'field' => 'book_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Doc No',
            'field' => 'document_number',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Date',
            'field' => 'document_date',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Location',
            'field' => 'store_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Vendor',
            'field' => 'vendor_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Indent No',
            'field' => 'indent',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'SO No',
            'field' => 'order',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Name',
            'field' => 'item_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Code',
            'field' => 'item_code',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Attributes',
            'field' => 'item_attributes',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'HSN',
            'field' => 'hsn_code',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'UOM',
            'field' => 'uom_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Order Qty',
            'field' => 'po_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Short Closed Qty',
            'field' => 'short_close_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Gate Entry Qty',
            'field' => 'ge_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Receipt Qty',
            'field' => 'grn_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Currency',
            'field' => 'vendor_currency',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Rate',
            'field' => 'rate',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Discount',
            'field' => 'total_discount_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Taxable Amt',
            'field' => 'taxable_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Tax',
            'field' => 'tax_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Total',
            'field' => 'total_item_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        // [
        //     'name' => 'Pending Qty',
        //     'field' => 'pending_qty',
        //     'header_class' => 'numeric-alignment',
        //     'column_class' => 'text-end pe-2_5',
        //     'header_style' => '',
        //     'column_style' => '',
        // ],
        [
            'name' => 'Status',
            'field' => 'status',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => 'text-align:center',
            'column_style' => '',
        ],
    ];
    const PO_FILTERS = [
        [
            'colSpan' => 'auto',
            'label' => 'Vendor',
            'id' => 'vendor_filter',
            'requestName' => 'vendor_id',
            'term' => 'vendor_list',
            'value_key' => 'id',
            'label_key' => 'company_name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Series',
            'id' => 'book_filter',
            'requestName' => 'book_id',
            'term' => 'report_so_book',
            'value_key' => 'id',
            'label_key' => 'book_code',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Doc No',
            'id' => 'doc_number_filter',
            'requestName' => 'document_number',
            'term' => 'report_so_documents',
            'value_key' => 'id',
            'label_key' => 'document_number',
            'type' => 'input_text'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Item Category',
            'id' => 'item_cat_filter',
            'requestName' => 'item_category_id',
            'term' => 'category',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['item_sub_cat_filter', 'item_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Item Sub Category',
            'id' => 'item_sub_cat_filter',
            'requestName' => 'item_sub_category_id',
            'term' => 'subcategory',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['item_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Items',
            'id' => 'item_filter',
            'requestName' => 'item_id',
            'term' => 'report_items',
            'value_key' => 'id',
            'label_key' => 'item_name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Status',
            'id' => 'doc_status_filter',
            'requestName' => 'doc_status',
            'term' => 'document_statuses',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Company',
            'id' => 'company_filter',
            'requestName' => 'company_id',
            'term' => 'companies',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['organization_filter']

        ],
        [
            'colSpan' => 'auto',
            'label' => 'Organization',
            'id' => 'organization_filter',
            'requestName' => 'organization_id',
            'term' => 'organizations',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['location_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Location',
            'id' => 'location_filter',
            'requestName' => 'location_id',
            'term' => 'location',
            'value_key' => 'id',
            'label_key' => 'store_name',
            'type' => 'auto_complete'
        ],
    ];
    const PI_TABLE_HEADERS = [
        [
            'name' => 'S. No',
            'field' => 'DT_RowIndex',
            'header_class' => '',
            'column_class' => '',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Series',
            'field' => 'book_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Doc No',
            'field' => 'document_number',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Date',
            'field' => 'document_date',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Location',
            'field' => 'store_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Requester Type',
            'field' => 'requester_type',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Requester',
            'field' => 'requester_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'So No',
            'field' => 'so_no',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Name',
            'field' => 'item_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Code',
            'field' => 'item_code',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Attributes',
            'field' => 'attributes',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'HSN',
            'field' => 'hsn_code',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'UOM',
            'field' => 'uom_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Indent Qty',
            'field' => 'po_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Order Qty',
            'field' => 'so_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Issue Qty',
            'field' => 'mi_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        // [
        //     'name' => 'Pending Qty',
        //     'field' => 'pending_qty',
        //     'header_class' => 'numeric-alignment',
        //     'column_class' => 'text-end pe-2_5',
        //     'header_style' => '',
        //     'column_style' => '',
        // ],
        [
            'name' => 'Status',
            'field' => 'status',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => 'text-align:center',
            'column_style' => '',
        ],
    ];
    const PI_FILTERS = [
        [
            'colSpan' => 'auto',
            'label' => 'Vendor',
            'id' => 'vendor_filter',
            'requestName' => 'vendor_id',
            'term' => 'vendor_list',
            'value_key' => 'id',
            'label_key' => 'company_name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Series',
            'id' => 'book_filter',
            'requestName' => 'book_id',
            'term' => 'report_so_book',
            'value_key' => 'id',
            'label_key' => 'book_code',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Doc No',
            'id' => 'doc_number_filter',
            'requestName' => 'document_number',
            'term' => 'report_so_documents',
            'value_key' => 'id',
            'label_key' => 'document_number',
            'type' => 'input_text'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Item Category',
            'id' => 'item_cat_filter',
            'requestName' => 'item_category_id',
            'term' => 'category',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['item_sub_cat_filter', 'item_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Item Sub Category',
            'id' => 'item_sub_cat_filter',
            'requestName' => 'item_sub_category_id',
            'term' => 'subcategory',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['item_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Items',
            'id' => 'item_filter',
            'requestName' => 'item_id',
            'term' => 'report_items',
            'value_key' => 'id',
            'label_key' => 'item_name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Status',
            'id' => 'doc_status_filter',
            'requestName' => 'doc_status',
            'term' => 'document_statuses',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Company',
            'id' => 'company_filter',
            'requestName' => 'company_id',
            'term' => 'companies',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['organization_filter']

        ],
        [
            'colSpan' => 'auto',
            'label' => 'Organization',
            'id' => 'organization_filter',
            'requestName' => 'organization_id',
            'term' => 'organizations',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['location_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Location',
            'id' => 'location_filter',
            'requestName' => 'location_id',
            'term' => 'location',
            'value_key' => 'id',
            'label_key' => 'store_name',
            'type' => 'auto_complete'
        ],
    ];
    const FILTERS_MAPPING = [
        ConstantHelper::SO_SERVICE_ALIAS => self::SO_FILTERS,
        ConstantHelper::SI_SERVICE_ALIAS => self::SI_FILTERS,
        ConstantHelper::SR_SERVICE_ALIAS => self::SR_FILTERS,
        ConstantHelper::MATERIAL_RETURN_SERVICE_ALIAS_NAME => self::MATERIAL_RETURN_SERVICE_ALIAS_NAME_FILTERS,
        ConstantHelper::MATERIAL_ISSUE_SERVICE_ALIAS_NAME => self::MATERIAL_ISSUE_SERVICE_ALIAS_NAME_FILTERS,
        ConstantHelper::MRN_SERVICE_ALIAS => mrnReportHelper::MRN_FILTERS,
        ConstantHelper::GATE_ENTRY_SERVICE_ALIAS => geReportHelper::GE_FILTERS,
        ConstantHelper::EXPENSE_ADVISE_SERVICE_ALIAS => expenseReportHelper::EXPENSE_FILTERS,
        ConstantHelper::PB_SERVICE_ALIAS => pbReportHelper::PB_FILTERS,
        ConstantHelper::PURCHASE_RETURN_SERVICE_ALIAS => prReportHelper::PR_FILTERS,
        ConstantHelper::PSV_SERVICE_ALIAS => self::PSV_FILTERS,
        ConstantHelper::PO_SERVICE_ALIAS => self::PO_FILTERS,
        ConstantHelper::PI_SERVICE_ALIAS => self::PI_FILTERS,
        ConstantHelper::PL_SERVICE_ALIAS => plReportHelper::PL_FILTERS,
        ConstantHelper::MO_SERVICE_ALIAS => moReportHelper::MO_FILTERS,
        ConstantHelper::BOM_SERVICE_ALIAS => bomReportHelper::BOM_FILTERS,
        ConstantHelper::RFQ_SERVICE_ALIAS => rfqReportHelper::RFQ_FILTERS,
        ConstantHelper::PQ_SERVICE_ALIAS => pqReportHelper::PQ_FILTERS,

    ];
    public static function initialize(): void
    {
        self::$TABLE_HEADERS = [
            ConstantHelper::SO_SERVICE_ALIAS => self::SO_TABLE_HEADERS,
            ConstantHelper::SO_SERVICE_ALIAS . 'attributeGrouped' => self::SO_ATTRIBUTE_GROUPED_TABLE_HEADERS,
            ConstantHelper::SI_SERVICE_ALIAS => self::SI_TABLE_HEADERS,
            ConstantHelper::SR_SERVICE_ALIAS => self::SR_TABLE_HEADERS,
            ConstantHelper::MATERIAL_RETURN_SERVICE_ALIAS_NAME => self::MATERIAL_RETURN_SERVICE_ALIAS_NAME_TABLE_HEADERS,
            ConstantHelper::MATERIAL_ISSUE_SERVICE_ALIAS_NAME => self::MATERIAL_ISSUE_SERVICE_ALIAS_NAME_TABLE_HEADERS,
            ConstantHelper::MRN_SERVICE_ALIAS => mrnReportHelper::MRN_TABLE_HEADERS,
            ConstantHelper::GATE_ENTRY_SERVICE_ALIAS => geReportHelper::GE_TABLE_HEADERS,
            ConstantHelper::EXPENSE_ADVISE_SERVICE_ALIAS => expenseReportHelper::EXPENSE_TABLE_HEADERS,
            ConstantHelper::PB_SERVICE_ALIAS => pbReportHelper::PB_TABLE_HEADERS,
            ConstantHelper::PURCHASE_RETURN_SERVICE_ALIAS => prReportHelper::PR_TABLE_HEADERS,
            ConstantHelper::PSV_SERVICE_ALIAS => self::PSV_TABLE_HEADERS,
            ConstantHelper::PO_SERVICE_ALIAS => self::PO_TABLE_HEADERS,
            ConstantHelper::PI_SERVICE_ALIAS => self::PI_TABLE_HEADERS,
            ConstantHelper::PL_SERVICE_ALIAS => plReportHelper::PL_TABLE_HEADERS,
            ConstantHelper::MO_SERVICE_ALIAS => moReportHelper::MO_TABLE_HEADERS,
            ConstantHelper::BOM_SERVICE_ALIAS => bomReportHelper::getBomTableHeaders('bill-of-material'),
            ConstantHelper::RFQ_SERVICE_ALIAS => rfqReportHelper::RFQ_TABLE_HEADERS,
            ConstantHelper::PQ_SERVICE_ALIAS => pqReportHelper::PQ_TABLE_HEADERS,
        ];
    }
    const DYNAMIC_FIELDS_SEPERATION_INDEX = [
        ConstantHelper::SO_SERVICE_ALIAS => 7
    ];
}
