<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>{{ $data['title'] }}</title>
    </head>

    <body>

        <div
            style="width:486px; padding:5px 57px 52px; background:#f6f6f6; border-top: #7415ae 8px solid; border-bottom: #7415ae 8px solid; font-family:Arial, Helvetica, sans-serif">
            <table cellpadding="0" cellspacing="0" width="100%">
                <tr>
                    <td style="text-align: center; padding: 17px 0">
                        <p><img src="logo.png" /></p>
                    </td>
                </tr>
            </table>
            <table cellpadding="0" cellspacing="0"
                style="background:#fff;  padding:50px 45px 0 40px; font-family:Arial, Helvetica, sans-serif"
                width="100%">
                <tbody>
                    <tr>
                        <td>
                            <p style="font-size:18px; margin: 0 0 25px"><strong>{{ ucfirst($data['title']) }}</strong>,</p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p style="margin:0 0 25px; font-size:15px; line-height: 25px">{{ $data['message'] }}</p>
                            <table style="width: 100%">
                                {{-- <tr>
                                    <td width="40px" style="padding: 10px 0; border-bottom: #eee thin solid">
                                        <img src="doc.png" />
                                    </td>
                                    <td
                                        style="padding: 10px 0; border-bottom: #eee thin solid; font-size: 14px; font-weight: bold">
                                        <a href="#" style="color: #000; text-decoration: none">Agreement file</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td style="padding: 10px 0; border-bottom: #eee thin solid; "><img src="doc.png" />
                                    </td>
                                    <td
                                        style="padding: 10px 0; border-bottom: #eee thin solid;  font-size: 14px; font-weight: bold">
                                        <a href="#" style="color: #000; text-decoration: none">Contract
                                            Agreement</a>
                                    </td>
                                </tr> --}}
                            </table>

                            <p style="margin:25px 0 10px; font-size:16px">Sincerely!</p>
                            <p style="margin:0 0 20px; font-size:16px">Presence360 Team,</p>
                            <p style="margin:45px 0 15px; font-size:11px; color: #A8A8A8; line-height: 15px;">Disclaimer
                                : *This communication is auto-generated by the system. In case of wrong delivery please
                                ignore this mail.</p>

                            <p style="text-align:left; color:#999; font-size:11px; margin-top: 0">
                                For more information, Please visit
                                <a href="{{ config('app.url') }}" style="color:#000">{{ config('app.url') }}</a>
                            </p>

                            <table cellpadding="0" cellspacing="0"
                                style="padding:10px; font-family:Tahoma, Geneva, sans-serif" width="100%">
                                <tbody>
                                    <tr>
                                        <td width="100%"></td>
                                    </tr>
                                    <tr>
                                        <td colspan="2"></td>
                                    </tr>
                                </tbody>
                            </table>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </body>

</html>
