<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Mailer</title>
</head>

<body style="background:#D0D0CE5a"> 

    <div
        style="width:680px; margin:0 auto; padding:50px 50px; background:#D0D0CE4a; font-family:Arial, Helvetica, sans-serif">

        <table cellpadding="0" cellspacing="0" width="100%" style="background: #7415ae">
            <tr>
                <td>
                    <p style="text-align: center; margin-bottom: 6px; margin: 30px"><img src="https://login.thepresence360.com/images/thepresence.png" height="30px" />
                    </p>

                </td>
            </tr>
        </table>
        <table cellpadding="0" cellspacing="0"
            style="background:#fff; box-shadow: 0 0 14px 0 #00000033; border:#ececec thin solid; padding:10px 20px; font-family:Tahoma, Geneva, sans-serif; border-bottom: 6px #7415ae solid"
            width="100%">
            <tbody>

                <tr>
                    <td>
                        <table cellpadding="0" cellspacing="0" width="100%">
                            <tbody>
                                <tr>
                                    <td valign="top">
                                        <p style="margin-bottom:0; font-size:17px; color:#777; line-height:27px">
                                            {!! $body->description !!}
                                        </p>

                                        <p style="margin:55px 0 10px; font-size:16px">Sincerely!</p>
                                        <p style="margin:0 0 20px; font-size:16px">Presence360 Team,</p>
                                        <p
                                            style="margin:45px 0 15px; font-size:11px; color: #A8A8A8; line-height: 15px;">
                                            Disclaimer : *This communication is auto-generated by the system. In case of
                                            wrong delivery please ignore this mail.</p>

                                        <p style="text-align:left; color:#999; font-size:11px; margin-top: 0">For more
                                            information, Please visit <a href="https://login.thepresence360.com/"
                                                style="color:#000">https://login.thepresence360.com</a></p>

                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>

            </tbody>


        </table>







    </div>

</body>

</html>
